Repository ISIS3510-202410-Team14/Kotlin, pull requests merged in 2024-05, with the labels that each got.

#39 Mensajes Error
  app/src/main/java/com/optic/moveon/view/AdaptadorNombres.kt
  app/src/main/java/com/optic/moveon/view/BusquedaVozActivity.kt
  app/src/main/java/com/optic/moveon/view/MapActivity.kt
Labels: code

#41 Error BQ type 2
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .gradle/buildOutputCleanup/outputFiles.bin
  .gradle/file-system.probe
  app/src/main/java/com/optic/moveon/view/UniversityActivity.kt
Labels: bug, code

#56 View #3 profile
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/optic/moveon/view/MainActivity.kt
  app/src/main/java/com/optic/moveon/view/ProfileActivity.kt
  app/src/main/java/com/optic/moveon/view/UniversityActivity.kt
  app/src/main/res/drawable/persona.png
  app/src/main/res/layout/activity_profile.xml
Labels: code

#57 Complementando view #3
  app/src/main/java/com/optic/moveon/model/entities/User.kt
  app/src/main/java/com/optic/moveon/view/EditActivity.kt
  app/src/main/java/com/optic/moveon/view/ProfileActivity.kt
  app/src/main/java/com/optic/moveon/view/RegisterActivity.kt
  app/src/main/res/layout/activity_edit.xml
Labels: enhancement, code

#61 Update connection Firebase upload documents
  app/src/main/java/com/optic/moveon/model/entities/User.kt
  app/src/main/java/com/optic/moveon/view/EditActivity.kt
  app/src/main/java/com/optic/moveon/view/ProfileActivity.kt
  app/src/main/java/com/optic/moveon/view/RegisterActivity.kt
  app/src/main/res/layout/activity_edit.xml
Labels: bug, code

#63 Almost completed feature #3
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/optic/moveon/view/EditActivity.kt
  app/src/main/res/layout/activity_edit.xml
Labels: enhancement, code

#67 Error solved Register/Auth
  app/src/main/java/com/optic/moveon/DefaultApp.kt
  app/src/main/java/com/optic/moveon/view/ProfileActivity.kt
  app/src/main/java/com/optic/moveon/viewmodel/MainViewModel.kt
Labels: bug

#68 update info document
  app/src/main/java/com/optic/moveon/view/UploadActivity.kt
Labels: code

#71 New Activity Added to the Manifest
  app/src/main/AndroidManifest.xml
  app/src/main/res/layout/activity_home.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_residence.xml
  app/src/main/res/layout/res_item.xml
  app/src/main/res/layout/residence_detail.xml
  app/src/main/res/layout/residence_item.xml
Labels: code

#74 Residences DAO and Main additionals
  app/src/main/java/com/optic/moveon/DefaultApp.kt
  app/src/main/java/com/optic/moveon/data/AppDataBase.kt
  app/src/main/java/com/optic/moveon/view/HomeActivity.kt
  app/src/main/java/com/optic/moveon/view/MainActivity.kt
  app/src/main/java/com/optic/moveon/view/UniversityActivity.kt
  app/src/main/java/com/optic/moveon/viewmodel/MainViewModel.kt
Labels: code

#76 Eventual Connectivity feature #3
  app/src/main/java/com/optic/moveon/view/EditActivity.kt
  app/src/main/java/com/optic/moveon/view/ProfileActivity.kt
Labels: bug

#78 Caching strategy feature #3
  app/src/main/java/com/optic/moveon/view/EditActivity.kt
Labels: enhancement

#83 Residence Details Working
  app/src/main/java/com/optic/moveon/model/entities/Residence.kt
  app/src/main/java/com/optic/moveon/view/ResAdapter.kt
  app/src/main/java/com/optic/moveon/view/ResidenceActivity.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_residence.xml
Labels: code

#85 Micro-Optimization #3
  app/src/main/java/com/optic/moveon/view/ProfileActivity.kt
Labels: code

#86 Micro-Optimization Residence Activity
  app/src/main/java/com/optic/moveon/view/ResidenceActivity.kt
Labels: code

#92 Vela micro optimization chat
  app/src/main/java/com/optic/moveon/view/ChatActivity2.kt
Labels: code

#94 Borrar archivo no usado
  app/src/main/java/com/optic/moveon/model/borrar.java
Labels: bug

#95 Deleted references to eliminated activities
  app/src/main/AndroidManifest.xml
Labels: code

#102 BQ #3 Angel Completed
  app/src/main/java/com/optic/moveon/view/UniversityActivity.kt
Labels: code

#105 Business Question Sprint 4
  app/src/main/java/com/optic/moveon/view/ResidenceActivity.kt
Labels: code
