Repository ISIS3510-202410-Team14/Kotlin, pull requests merged in 2024-04, with the labels that each got.

#20 UPDATE ANGEL Branch
  .gradle/8.2/checksums/checksums.lock
  .gradle/8.2/checksums/md5-checksums.bin
  .gradle/8.2/checksums/sha1-checksums.bin
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/optic/moveon/model/UserSessionManager.kt
  app/src/main/java/com/optic/moveon/model/entities/Chat.kt
  app/src/main/java/com/optic/moveon/view/AdapterChat.kt
  app/src/main/java/com/optic/moveon/view/ChatActivity2.kt
  app/src/main/java/com/optic/moveon/view/MainActivity.kt
  app/src/main/res/layout/activity_chat2.xml
  app/src/main/res/layout/chat_detail_item.xml
Labels: bug

#22 Eventual Connectivity in User Registration
  .gitignore
  app/build.gradle.kts
  app/src/main/java/com/optic/moveon/model/UserSessionManager.kt
  app/src/main/java/com/optic/moveon/view/RegisterActivity.kt
  app/src/main/res/layout/dialog_wait.xml
Labels: enhancement

#23 BusquedaVoz Connectivity Strategie
  app/src/main/java/com/optic/moveon/view/BusquedaVozActivity.kt
Labels: code

#25 Eventual Connectivity and Cache AuthActivity
  .gitignore
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/optic/moveon/DefaultApp.kt
  app/src/main/java/com/optic/moveon/data/AppDataBase.kt
  app/src/main/java/com/optic/moveon/data/UniversityDAO.kt
  app/src/main/java/com/optic/moveon/model/entities/LocalUniversity.kt
  app/src/main/java/com/optic/moveon/view/AdapterUniversity.kt
  app/src/main/java/com/optic/moveon/view/AuthActivity.kt
  app/src/main/java/com/optic/moveon/view/MainActivity.kt
  app/src/main/java/com/optic/moveon/view/UniversityActivity.kt
Labels: enhancement, code

#26 Multi-Threading in Authentication
  .gradle/8.2/checksums/md5-checksums.bin
  app/src/main/java/com/optic/moveon/view/AuthActivity.kt
Labels: code

#27 Local Storage Favorites Universities
  .idea/deploymentTargetDropDown.xml
  app/build.gradle.kts
  app/src/main/java/com/optic/moveon/data/UniversityDAO.kt
  app/src/main/java/com/optic/moveon/model/entities/LocalUniversity.kt
  app/src/main/java/com/optic/moveon/view/MainActivity.kt
  app/src/main/java/com/optic/moveon/view/UniversityActivity.kt
  app/src/main/java/com/optic/moveon/viewmodel/MainViewModel.kt
  app/src/main/res/layout/activity_university.xml
Labels: enhancement, code

#30 Multi-Threading for RegisterActivity
  app/src/main/java/com/optic/moveon/view/RegisterActivity.kt
Labels: code

#31 Business Question Type 1 - Event
  app/src/main/java/com/optic/moveon/view/AuthActivity.kt
Labels: code

#34 Implement analytics for tracking most favorited university
  app/src/main/java/com/optic/moveon/view/AdapterUniversity.kt
Labels: enhancement, code

#37 udpate last changes froms universitys
  .gradle/file-system.probe
  app/src/main/java/com/optic/moveon/view/AdapterUniversity.kt
Labels: bug
